FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

# Instalar Playwright e suas dependências
RUN npx playwright install chromium firefox webkit
RUN npx playwright install-deps

EXPOSE 80
CMD ["npm", "run", "start"]
