name: ci

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/Backend/PriceWatch.sln
      - name: Build
        run: dotnet build --no-restore --configuration Release src/Backend/PriceWatch.sln
      - name: Test
        run: dotnet test --no-build --configuration Release src/Backend/PriceWatch.Tests/PriceWatch.Tests.csproj
